Attribute VB_Name = "FilePaths"
'Declare global and const

'PCC Set Up
Public Const strDivisionIni = "C:\Users\tao\Box Sync\1. Clients\Porirua City Council\PCC Templates 2012\Settings files\Division.ini" '###"W:\!Common\Templates\Office_2010\Division.ini"
Public Const strQuoteIni = "C:\Users\tao\Box Sync\1. Clients\Porirua City Council\PCC Templates 2012\Settings files\Quote.ini" '###"W:\!Common\Templates\Office_2010\Quote.ini"
Public Const strDefaultUserIni = "C:\Users\tao\Box Sync\1. Clients\Porirua City Council\PCC Templates 2012\Settings files\User.ini" '###"H:\User.ini"
Public Const strWebIni = "C:\Users\tao\Box Sync\1. Clients\Porirua City Council\PCC Templates 2012\Settings files\web.ini" '###"W:\!Common\Templates\Office_2010\web.ini"

' Allfields Setup
'Public Const strDivisionIni = "H:\Division.ini"
'Public Const strQuoteIni = "H:\quote.ini"
'Public Const strWebIni = "H:\web.ini"
'Public Const strDefaultUserIni = "C:\Template_Toolkit\Set_Up\user.ini"


Public Const MAX_INI_WRITE_ATTEMPTS = 3
Public Const FILE_VERSION = "4.1"
Public Const LAST_UPDATED = "24/07/2012 3:30pm"
Public Const LAST_AUTHOR = "Allfields"

Public strWorkgroupTemplatesPath As String
Public TOOLKIT_LOADED As Boolean

Public strTemplatesPath As String
Public strUserIniPath As String
Public strUserIni As String
Dim oAppClass As ThisApplication
Public IniOP As INIHelper

Sub Autoexec()
    Call CreateEventHandler

    If Not TOOLKIT_LOADED Then
        ' Get the default path from the Workgroup Templates directive in Word
        strWorkgroupTemplatesPath = "C:\Users\tao\Box Sync\1. Clients\Porirua City Council\PCC Templates 2012\Office 2010 Templates" 'Options.DefaultFilePath(wdWorkgroupTemplatesPath)
                
        strTemplatesPath = strWorkgroupTemplatesPath & "\"
        strUserIniPath = strDefaultUserIni
        strUserIni = strUserIniPath & "\User.ini"
        
        Set IniOP = New INIHelper

        TOOLKIT_LOADED = True
        
    End If
    
End Sub

Sub AutoExit()
    DestroyEventHandler
End Sub

Sub CreateEventHandler()
    Set oAppClass = New ThisApplication
    Set oAppClass.oApp = Word.Application
End Sub

Sub DestroyEventHandler(Optional Force As Boolean = False)
    If Force Or Documents.count <= 1 Then
        Set oAppClass = Nothing
    End If
End Sub

Function CheckRequirements(Optional RequireUserIni As Boolean = True) As Boolean
 
    If Not FolderExists(strTemplatesPath) Then _
        ThrowFatalError "There does not appear to be a folder for templates." & vbCr & _
                            "Looking in: " & strTemplatesPath
    
End Function

Private Sub CreateNewUserIni()

    Dim fso As FileSystemObject
    Dim FSOFile As TextStream
    Set fso = New FileSystemObject
    If Not FileExists(strUserIni) Then
        NewIniPath = strUserIni
        Set FSOFile = fso.OpenTextFile(NewIniPath, 2, True)
        With FSOFile
            .WriteLine ("; User INI Configuration file for PCC.")
            .WriteLine ("; Generated on " & Format(Date, "dd/mm/yyyy") & " by the Template Toolkit")
            .WriteLine ("; This file is edited by the Template Toolkit, do not edit this file directly")
            .WriteBlankLines (2)
            .Close
        End With
    End If

End Sub
